# Generated by Django 5.1.5 on 2025-05-24 13:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('appointment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('appointment_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('appointment_type', models.CharField(choices=[('consultation', 'General Consultation'), ('follow_up', 'Follow-up Visit'), ('checkup', 'Regular Checkup'), ('emergency', 'Emergency'), ('physical_therapy', 'Physical Therapy'), ('lab_work', 'Lab Work'), ('imaging', 'Imaging')], db_index=True, default='consultation', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=15)),
                ('patient_notes', models.TextField(blank=True, help_text="Patient's notes or symptoms")),
                ('doctor_notes', models.TextField(blank=True, help_text="Doctor's notes after appointment")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['-appointment_date', '-start_time'],
                'indexes': [models.Index(fields=['appointment_date', 'start_time'], name='appointment_appoint_e54e0a_idx'), models.Index(fields=['patient', 'status'], name='appointment_patient_6fe260_idx'), models.Index(fields=['doctor', 'status'], name='appointment_doctor__45f502_idx'), models.Index(fields=['appointment_date', 'status'], name='appointment_appoint_b9472b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='account.doctorprofile')),
            ],
            options={
                'db_table': 'doctor_availability',
                'indexes': [models.Index(fields=['doctor', 'day_of_week'], name='doctor_avai_doctor__b54d61_idx'), models.Index(fields=['doctor', 'is_available'], name='doctor_avai_doctor__cc163b_idx')],
                'unique_together': {('doctor', 'day_of_week', 'start_time')},
            },
        ),
    ]
