# Generated by Django 5.1.5 on 2025-05-24 13:23

import app.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('admin', 'Admin')], db_index=True, default='patient', max_length=10)),
                ('phone', models.CharField(blank=True, help_text='Phone number in international format', max_length=17, validators=[app.core.validators.validate_phone_number])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=17, validators=[app.core.validators.validate_phone_number])),
                ('medical_history', models.TextField(blank=True, help_text="Patient's medical history, allergies, etc.")),
                ('insurance_info', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('license_number', models.CharField(help_text='Medical license number in format: ABC-123456', max_length=50, unique=True, validators=[app.core.validators.validate_medical_license])),
                ('specialty', models.CharField(db_index=True, max_length=100)),
                ('subspecialty', models.CharField(blank=True, max_length=100)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('hospital_affiliation', models.CharField(blank=True, max_length=200)),
                ('clinic_address', models.TextField(blank=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('accepts_new_patients', models.BooleanField(default=True)),
                ('user_profile', models.OneToOneField(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
            options={
                'db_table': 'doctor_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='user_profil_role_fa03e1_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user', 'role'], name='user_profil_user_id_abd701_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['specialty'], name='doctor_prof_special_ba816a_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['is_available'], name='doctor_prof_is_avai_8ad711_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['specialty', 'is_available'], name='doctor_prof_special_927377_idx'),
        ),
    ]
